feedback/urls.py
from django.conf.urls.defaults import *

from feedback.views import leave_feedback

urlpatterns = patterns('',
    url(r'^$', leave_feedback, name='leave-feedback'),
)

feedback/models.py
from django.utils.translation import ugettext_lazy as _
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.conf import settings
from django.core.mail import mail_admins
from django.template import Context
from django.template.loader import get_template

class BaseFeedback(models.Model):
    class Meta:
        abstract = True
        ordering = ['-time']

    type = models.CharField(choices=settings.FEEDBACK_CHOICES, max_length=100, verbose_name=_('Type'))
    message = models.TextField(verbose_name=_('Message'))
    time = models.DateTimeField(auto_now_add=True, verbose_name=_('Time'))
    context = models.TextField(verbose_name=_('Context'))

    def __unicode__(self):
        return self.message

    def get_absolute_url(self):
        return reverse('admin:view-feedback', args=[self.id])


class Feedback(BaseFeedback):
    user = models.ForeignKey(User, verbose_name=_('User'))


class AnonymousFeedback(BaseFeedback):
    user = models.ForeignKey(User, verbose_name=_('User'), null=True, blank=True, default=None)
    email = models.EmailField()


@receiver(post_save, sender=AnonymousFeedback)
@receiver(post_save, sender=Feedback)
def notify_admin_feedback(sender, instance, created, **kwargs):
    """Email admin whenever feedback is saved."""
    if created:
        c = Context({
            'message': instance.message,
            'from': instance.user,
            'email': getattr(instance, 'email', None)
            })
        t = get_template('feedback/feedback_message.txt')
        mail_admins(
            "Feedback",
            t.render(c),
            fail_silently=False,
            connection=None,
            html_message=None)

feedback/forms.py
from django import forms

from feedback.models import Feedback, AnonymousFeedback


class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        exclude = ('user', 'context', )


class AnonymousFeedbackForm(forms.ModelForm):
    class Meta:
        model = AnonymousFeedback
        exclude = ('user', 'context', )

    def __init__(self, *args, **kwargs):
        super(AnonymousFeedbackForm, self).__init__(*args, **kwargs)
        self.fields.keyOrder = [
            'email',
            'type',
            'message',
        ]

feedback/views.py
from django.utils.translation import ugettext as _

from django.shortcuts import render_to_response
from django.template import RequestContext

from feedback.forms import FeedbackForm


def leave_feedback(
        request,
        template_name='feedback/feedback_form.html'):

    form = FeedbackForm(request.POST or None)
    if form.is_valid():
        feedback = form.save(commit=False)
        feedback.user = request.user
        feedback.context = ''
        feedback.save()
        url = request.POST.get('next', request.META.get('HTTP_REFERER', '/'))
        return render_to_response(template_name, {
            'message': _("Your feedback has been saved successfully.")
        }, context_instance=RequestContext(request))

    return render_to_response(
        template_name, {
            'feedback_form': form
        }, context_instance=RequestContext(request))

feedback/templates/feedback/feedback_form.html
{% extends "base.html" %}
{% block title %}Leave some feedback{% endblock %}
{% block main_content %}
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ feedback_form.as_table }}
            <tr>
                <td colspan='2'>
                    <input type="submit" value="Leave feedback" />
                </td>
            </tr>
        </table>
    </form>
{% endblock %}

feedback/templates/feedback/index.html
{% extends "admin/index.html" %}
{% load url from future %}
{% load i18n feedback_tags %}
{% block extrahead %}
    <style type='text/css'>
    #feedback {float:right;margin-right:-38em;width:18em;position:relative;}
    </style>
    {{ block.super }}
{% endblock %}
{% block sidebar %}
    {{ block.super }}
    <div id="feedback">
        <div class="module" id="feedback-module">
            <h2>{% trans 'Feedback' %}</h2>
            <ul class='actionlist'>
                {% get_feedback %}
                {% for feedback in feedback %}
                    <li><a href="{{ feedback.get_absolute_url }}">{{ feedback.get_type_display }} from {{ feedback.user.username|title }}</a> &mdash; {{ feedback.time|timesince }} ago</li>
                {% endfor %}
            </ul>
            <p><a href='{% url 'admin:feedback_feedback_changelist' %}'>View all feedback</a></p>
        </div>
    </div>
{% endblock %}

feedback/templates/feedback/view_feedback.html
{% extends "admin/change_form.html" %}
{% load i18n %}
{% block breadcrumbs %}{% if not is_popup %}
<div class="breadcrumbs">
     <a href="../../../../">{% trans "Home" %}</a> &rsaquo;
     <a href="../../../">{% trans "Feedback" %}</a> &rsaquo; 
     Viewing Feedback
</div>
{% endif %}{% endblock %}
{% block content %}
    <div id="content-main">
        <fieldset class="module aligned">
            <h2>{{ feedback.get_type_display }} from {{ feedback.user|title }} &mdash; {{ feedback.time|timesince }} ago</h2>
            <p>{{ feedback.message }}</p>
            <h3>Actions</h3>
            <ul>
                <li><a href='mailto:{{ feedback.user.email }}'>E-mail user</a></li>
                <li><a href='../../{{ feedback.id }}/'>Edit Feedback</a></li>
                <li><a href='../../{{ feedback.id }}/delete/'>Delete Feedback</a></li>
            </ul>
        </fieldset>
    </div>
{% endblock %}